#!/bin/bash

##
# Script to load ssh keys into ssh-agent or gnome-keyring.
##

KEYS="dsa rsa"
for key in $KEYS ; do
  if [ -f "~/.ssh/id_$key" ] ; then
    TEMP=`mktemp`
    chmod 700 $TEMP
    echo -e "#!/bin/bash\n$HOME/bin/keyring get id_$key" > $TEMP
    SSH_ASKPASS="$TEMP" ssh-add ~/.ssh/id_$key < /dev/null
    rm $TEMP
  fi
done
