#!/bin/bash

##
# Script to load ssh keys into ssh-agent or gcr-ssh-agent
# gcr setup:
#   - install gcr-4 package
#   - $ systemctl enable --user --now gcr-ssh-agent.socket
##

export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh
for key in $(find ~/.ssh -maxdepth 1 -name "id_*") ; do
  TEMP=$(mktemp)
  chmod 700 $TEMP
  echo -e "#!/bin/bash\n$HOME/bin/keyring get $(basename $key)" > $TEMP
  SSH_ASKPASS="$TEMP" ssh-add $key < /dev/null
  rm $TEMP
done
