#!/bin/bash

##
# Script to load ssh keys into ssh-agent or gnome-keyring.
##

for key in $(find ~/.ssh -maxdepth 1 -name "id_*") ; do
  TEMP=`mktemp`
  chmod 700 $TEMP
  echo -e "#!/bin/bash\n$HOME/bin/keyring get $(basename $key)" > $TEMP
  SSH_ASKPASS="$TEMP" ssh-add $key < /dev/null
  rm $TEMP
done
