#!/bin/bash

##
# Script to load gpg keys into gpg-agent.
##

IFS=$'\n'
for uid in $(gpg2 --list-secret-keys | grep "^uid\>" | sed 's/^uid\s\+//') ; do
  keygrip=$(
    gpg2 --fingerprint --fingerprint "$uid" |
    sed -ne '/.*sub/,$p' |
    sed -ne '1,/Key fingerprint = .*/p' |
    grep "Key fingerprint" |
    sed 's/\s*Key fingerprint = //' |
    sed 's/\s//g'
  )
  #echo "gpg preset: $uid ($keygrip)"
  keyring get "$uid" | /usr/lib/gnupg/gpg-preset-passphrase --preset $keygrip
done
