#!/bin/bash

##
# pre-push hook which prevents a force push to master, staging, and sprint*
# branches.
##

local_branch="$(git rev-parse --abbrev-ref HEAD)"

IFS=' '
z40=0000000000000000000000000000000000000000
while read local_ref local_sha remote_ref remote_sha ; do
  if [ $remote_sha = $z40 ] ; then
    continue
  fi
  contains_remote=$(git branch --contains $remote_sha | grep "\<$local_branch\>")
  if [ -z "$contains_remote" ] ; then
    remote_branch="$(basename $remote_ref)"
    case "$remote_branch" in
      master|staging|sprint*)
        echo "Force pushing to $remote_branch is not permitted."
        exit 1
    esac
  fi
done

exit 0
