#!/bin/bash

##
# pre-rebase hook which runs my 'rebasesafe' alias to prevent silly mistakes
# when running rebase.
#
# Prevents rebasing if any of the commits to be rebased are found in another
# branch.
##

if [ "$#" -eq 2 ] ; then
  topic="refs/heads/$2"
else
  topic=$(git symbolic-ref HEAD 2> /dev/null) ||
  exit 0 ; # don't interrupt rebasing detached HEAD
fi

git rebasesafe $1

exit $?
