#!/bin/bash

# shutdown eclim instances
if [ -f "$HOME/.eclim/.eclimd_instances" ] ; then
  echo "shutdown eclim..."
  for line in $(cat $HOME/.eclim/.eclimd_instances) ; do
    port=$(echo "$line" | jshon -e port)
    /opt/eclipse/eclim -Dnailgun.server.port=$port -command shutdown
  done

  # wait on all instance to fully stop
  while [ -n "$(pgrep -f org.eclim.application)" ] ; do
    sleep 1
  done
fi
