#!/bin/bash

# stop offlineimap loop + wait on existing process
if [ -n "$(pgrep -f ~/bin/offlineimap)" ] ; then
  pkill -f ~/bin/offlineimap
  PREV=""
  while [ -n "$(pgrep -f 'offlineimap\>.*-o')" ] ; do
    if [ -z "$PREV" ] ; then
      echo "waiting on offlineimap..."
    fi
    LINE=`tail -1 ~/.offlineimap/log`
    if [ "$LINE" != "$PREV" ] ; then
      echo -e "\t$LINE"
      PREV="$LINE"
    fi
    sleep 1
  done

  pkill -9 -f bin/offlineimap || true
fi
