backend = "xrender";

rules = (
  # match unfocused windows
  { match = "!focused"; dim = 0.4; },
  # match browser hover tooltip
  { match = "window_type = 'tooltip'" ; dim = 0.0; },
  # match browser right click menu (and possibly others)
  { match = "window_type *= 'menu'" ; dim = 0.0; },
  # match <select> dropdown in qutebrowser
  # (xprop: the first entry for _NET_WM_WINDOW_TYPE)
  {
    match = "_NET_WM_WINDOW_TYPE:a = '_KDE_NET_WM_WINDOW_TYPE_OVERRIDE'" ;
    dim = 0.0;
  },
  # match dock (eg: polybar)
  { match = "window_type = 'dock'" ; dim = 0.0; },
);
