#!/bin/bash

if [ ! -f $HOME/.backup.log ] ; then
  echo "never"
  exit 1
else
  seconds=$(($(date +%s) - $(stat --format=%Y $HOME/.backup.log)))
  hours=$((seconds / 60 / 60))
  days=$((seconds / 60 / 60 / 24))
  retcode=$(tail -n 1 $HOME/.backup.log | sed 's|^.*:\s\([0-9]\+\)$|\1|')
  if [ $days -eq 0 ] ; then
    if [ $hours -lt 1 ] ; then
      diff="<1 hr ago"
    elif [ $hours -eq 1 ] ; then
      diff="1 hr ago"
    else
      diff="$hours hrs ago"
    fi
  elif [ $days -le 1 ] ; then
    diff="1 day ago"
  else
    diff="$days days ago"
  fi

  echo $diff

  if [ "$retcode" != "0" ] ; then
    exit 1
  fi
fi
