#!/bin/bash

percent=$(pacmd list-cards | grep bluetooth.battery | sed 's|.*"\(.*\)%"|\1|')
if [ -n "$percent" ]; then
  if [ $percent -le 70 ] ; then
    percent="$percent%"
    echo $percent
    exit 1
  fi
  percent="$percent%"
  echo $percent
else
  echo ""
fi
