#!/bin/bash

service=$(systemctl --no-pager list-units *vpn*service* | grep 'vpn.*active')
service=$(echo $service | perl -pe "s|.*@(.*?)\.service.*|\1|")
service=$(echo $service | perl -pe "s|\s*(.*?)\.service.*|\1|")
if [ -n "$service" ] ; then
  echo $service
else
  echo ""
fi
